CREATE TABLE person_audit
(
    id bigint generated by default as identity primary key,
    name varchar not null,
    age integer not null default 10,
    gender varchar default 'female' not null ,
    address varchar,
    created timestamp with time zone default current_timestamp not null,
    type_event char(1) default 'I' not null,
    row_id bigint not null references person(id)
);

ALTER TABLE person_audit ADD constraint ch_type_event CHECK (type_event IN ('I', 'U', 'D'));

CREATE OR REPLACE FUNCTION fnc_trg_person_insert_audit()
RETURNS trigger AS $$
BEGIN
    INSERT INTO person_audit(name, age, gender, address, type_event, row_id)
    VALUES (NEW.name, NEW.age, NEW.gender, NEW.address, 'I', NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_person_insert_audit
AFTER INSERT ON person
FOR EACH ROW
EXECUTE FUNCTION fnc_trg_person_insert_audit();

INSERT INTO person(id, name, age, gender, address) VALUES (10,'Damir', 22, 'male', 'Irkutsk');
